trigger: none

pr:
- develop
- master

pool:
  vmImage: ubuntu-latest

steps:
- task: NodeTool@0
  displayName: 'Install Node 20'
  inputs:
    versionSpec: '20.x'

- task: CmdLine@2
  displayName: 'Install dependencies'
  inputs:
    script: |
      npm install

- task: CmdLine@2
  displayName: 'Run Lint'
  inputs:
    script: 'npm run lint'

- task: Npm@1
  displayName: 'Run Tests'
  inputs:
    command: 'custom'
    customCommand: 'test -- --ci --reporters=jest-junit --reporters=default --coverage --coverageReporters=cobertura'

- task: PublishTestResults@2
  displayName: 'Publish Unit Tests Results'
  inputs:
    testResultsFiles: junit.xml
    mergeTestResults: true
    testRunTitle: 'Transactional Frontend Pull Request Unit Test Results'
    failTaskOnFailedTests: true

- task: PublishCodeCoverageResults@1
  displayName: 'Publish Unit Tests Coverage'
  inputs:
    codeCoverageTool: Cobertura
    summaryFileLocation: coverage/cobertura-coverage.xml

- task: CmdLine@2
  displayName: 'Run Build'
  inputs:
    script: 'npm run build:ssr'
