export enum OrganisationErrorsEnum {
  ORGANISATION_NOT_FOUND = 'O.0001',
  ORGANISATIONS_NOT_FOUND = 'O.0002',
  ORGANISATION_UNIT_NOT_FOUND = 'O.0003',
  ORGANISATION_UNITS_NOT_FOUND = 'O.0004',
  ORGANISATION_UNIT_ACTIVATE_NO_QA = 'O.0005',
  ORGANISATION_ALREADY_EXISTS = 'O.0006',
  ORGANISATION_UNIT_ALREADY_EXISTS = 'O.0007',
  ORGANISATION_USER_NOT_FOUND = 'O.0008',
  ORGANISATION_USER_FROM_OTHER_ORG = 'O.0009',
  ORGANISATION_UNIT_USER_ALREADY_EXISTS = 'O.0010',
  ORGANISATION_UNIT_USER_CANT_BE_INNOVATOR = 'O.0011',
  ORGANISATION_NHSE_ACRONYM_CANNOT_BE_CHANGED = 'O.0013'
}
