export const dummy_innovation_data_V3_202405 = {
  name: '06-12-2023',
  description: '06-12',
  officeLocation: 'basedOutsideUk',
  countryLocation: ['portugal'],
  hasWebsite: 'no',
  categories: ['travelTransport', 'foodNutrition'],
  mainCategory: 'foodNutrition',
  areas: ['independenceAndPrevention', 'improvingSystemFlow'],
  careSettings: ['endLifeCare', 'careHomesCareSetting'],
  mainPurpose: 'monitorCondition',
  supportDescription: 'asd',
  currentlyReceivingSupport: 'asd',
  involvedAACProgrammes: ['no'],
  hasCostKnowledge: 'detailedEstimate',
  costDescription: 'asd',
  patientsRange: 'notSure',
  eligibilityCriteria: 'asd',
  sellExpectations: 'asd',
  usageExpectations: 'asd',
  costComparison: 'notSure',
  innovationPathwayKnowledge: 'pathwayExistsAndChanged',
  potentialPathway: 'asd',
  hasDeployPlan: 'yes',
  isDeployed: 'no',
  hasResourcesToScale: 'no',
  hasEvidence: 'notYet',
  currentlyCollectingEvidence: 'yes',
  summaryOngoingEvidenceGathering: 'asd',
  needsSupportAnyArea: ['dataSharing', 'approvalDataStudies', 'understandingLaws'],
  hasPatents: 'hasNone',
  hasOtherIntellectual: {
    response: 'yes',
    conditional: 'asdf'
  },
  hasMarketResearch: 'notYet',
  hasRegulationKnowledge: 'yesAll',
  hasRevenueModel: 'no',
  involvedUsersDesignProcess: 'inProgress',
  testedWithIntendedUsers: 'inProgress',
  intendedUserGroupsEngaged: ['clinicalSocialCareWorkingOutsideUk'],
  problemsTackled: 'tasdadasd',
  howInnovationWork: 'asd',
  benefitsOrImpact: [
    'enablesATest,ProcedureOrTreatmentToBeDoneNon-Invasively',
    'avoidsATest,ProcedureOrUnnecessaryTreatment'
  ],
  impactDiseaseCondition: 'yes',
  diseasesConditionsImpact: ['respiratoryConditionsAsthma'],
  estimatedCarbonReductionSavings: 'yes',
  carbonReductionPlan: 'yes',
  keyHealthInequalities: ['none'],
  completedHealthInequalitiesImpactAssessment: 'no'
};
