export enum UserRoleEnum {
  ADMIN = 'ADMIN',
  INNOVATOR = 'INNOVATOR',
  ACCESSOR = 'ACCESSOR',
  ASSESSMENT = 'ASSESSMENT',
  QUALIFYING_ACCESSOR = 'QUALIFYING_ACCESSOR'
}

export enum InnovatorOrganisationRoleEnum {
  INNOVATOR_OWNER = 'INNOVATOR_OWNER'
}

export enum AccessorOrganisationRoleEnum {
  ACCESSOR = 'ACCESSOR',
  QUALIFYING_ACCESSOR = 'QUALIFYING_ACCESSOR'
}

export enum TermsOfUseTypeEnum {
  INNOVATOR = 'INNOVATOR',
  SUPPORT_ORGANISATION = 'SUPPORT_ORGANISATION'
}
