export enum UserTypeEnum {
  ADMIN = 'ADMIN',
  ASSESSMENT = 'ASSESSMENT',
  ACCESSOR = 'ACCESSOR',
  INNOVATOR = 'INNOVATOR'
}

export enum UserRoleEnum {
  SERVICE_TEAM = 'SERVICE_TEAM',
  ADMIN = 'ADMIN',
  INNOVATOR = 'INNOVATOR',
  ACCESSOR = 'ACCESSOR',
  ASSESSMENT = 'ASSESSMENT',
  QUALIFYING_ACCESSOR = 'QUALIFYING_ACCESSOR',
}


export enum InnovatorOrganisationRoleEnum {
  INNOVATOR_OWNER = 'INNOVATOR_OWNER'
}

export enum AccessorOrganisationRoleEnum {
  ACCESSOR = 'ACCESSOR',
  QUALIFYING_ACCESSOR = 'QUALIFYING_ACCESSOR'
}


export enum TermsOfUseTypeEnum {
  INNOVATOR = 'INNOVATOR',
  SUPPORT_ORGANISATION = 'SUPPORT_ORGANISATION'
}
