export enum UserStatisticsTypeEnum {
  WAITING_ASSESSMENT_COUNTER = 'WAITING_ASSESSMENT_COUNTER',
  INNOVATIONS_ASSIGNED_TO_ME_COUNTER = 'INNOVATIONS_ASSIGNED_TO_ME_COUNTER',
  ACTIONS_TO_REVIEW_COUNTER = 'ACTIONS_TO_REVIEW_COUNTER',
  INNOVATIONS_TO_REVIEW_COUNTER = 'INNOVATIONS_TO_REVIEW_COUNTER'
}

export enum InnovationStatisticsEnum {
  SECTIONS_SUBMITTED_COUNTER= 'SECTIONS_SUBMITTED_COUNTER',
  ACTIONS_TO_SUBMIT_COUNTER = 'ACTIONS_TO_SUBMIT_COUNTER',
  UNREAD_MESSAGES_COUNTER = 'UNREAD_MESSAGES_COUNTER',
  ACTIONS_TO_REVIEW_COUNTER = 'ACTIONS_TO_REVIEW_COUNTER',
  SECTIONS_SUBMITTED_SINCE_SUPPORT_START_COUNTER = 'SECTIONS_SUBMITTED_SINCE_SUPPORT_START_COUNTER'
}

export enum InnovationSectionEnum {
  INNOVATION_DESCRIPTION = 'Description of innovation',
  VALUE_PROPOSITION = 'Value proposition',
  UNDERSTANDING_OF_NEEDS = 'Detailed understanding of needs',
  UNDERSTANDING_OF_BENEFITS = 'Detailed understanding of benefits',
  EVIDENCE_OF_EFFECTIVENESS = 'Evidence of effectiveness',
  MARKET_RESEARCH = 'Market research',
  INTELLECTUAL_PROPERTY = 'Intellectual property',
  REGULATIONS_AND_STANDARDS = 'Standards and certifications',
  CURRENT_CARE_PATHWAY = 'Current care pathway',
  TESTING_WITH_USERS = 'Testing with users',
  COST_OF_INNOVATION = 'Cost of your innovation',
  COMPARATIVE_COST_BENEFIT = 'Comparative cost benefit',
  REVENUE_MODEL = 'Revenue model',
  IMPLEMENTATION_PLAN = 'Implementation plan and deployment'
}
