export enum UserStatisticsTypeEnum {
  WAITING_ASSESSMENT_COUNTER = 'WAITING_ASSESSMENT_COUNTER',
  INNOVATIONS_ASSIGNED_TO_ME_COUNTER = 'INNOVATIONS_ASSIGNED_TO_ME_COUNTER',
  ACTIONS_TO_REVIEW_COUNTER = 'ACTIONS_TO_REVIEW_COUNTER',
  INNOVATIONS_TO_REVIEW_COUNTER = 'INNOVATIONS_TO_REVIEW_COUNTER'
}

export enum InnovationStatisticsEnum {
  SECTIONS_SUBMITTED_COUNTER= 'SECTIONS_SUBMITTED_COUNTER',
  ACTIONS_TO_SUBMIT_COUNTER = 'ACTIONS_TO_SUBMIT_COUNTER',
  UNREAD_MESSAGES_COUNTER = 'UNREAD_MESSAGES_COUNTER',
  ACTIONS_TO_REVIEW_COUNTER = 'ACTIONS_TO_REVIEW_COUNTER',
  SECTIONS_SUBMITTED_SINCE_SUPPORT_START_COUNTER = 'SECTIONS_SUBMITTED_SINCE_SUPPORT_START_COUNTER'
}
