export enum UserStatisticsTypeEnum {
  WAITING_ASSESSMENT_COUNTER = 'WAITING_ASSESSMENT_COUNTER',
  ASSIGNED_INNOVATIONS_COUNTER = 'ASSIGNED_INNOVATIONS_COUNTER',
  INNOVATIONS_ASSIGNED_TO_ME_COUNTER = 'INNOVATIONS_ASSIGNED_TO_ME_COUNTER',
  ACTIONS_TO_REVIEW_COUNTER = 'ACTIONS_TO_REVIEW_COUNTER',
  INNOVATIONS_TO_REVIEW_COUNTER = 'INNOVATIONS_TO_REVIEW_COUNTER'
};

export enum InnovationStatisticsEnum {
  ACTIONS_TO_SUBMIT_COUNTER = 'ACTIONS_TO_SUBMIT_COUNTER',
  SECTIONS_SUBMITTED_COUNTER= 'SECTIONS_SUBMITTED_COUNTER',
  UNREAD_MESSAGES_COUNTER = 'UNREAD_MESSAGES_COUNTER',
  ACTIONS_TO_REVIEW_COUNTER = 'ACTIONS_TO_REVIEW_COUNTER',
  SECTIONS_SUBMITTED_SINCE_SUPPORT_START_COUNTER = 'SECTIONS_SUBMITTED_SINCE_SUPPORT_START_COUNTER',
  SECTIONS_SUBMITTED_SINCE_ASSESSMENT_START_COUNTER = 'SECTIONS_SUBMITTED_SINCE_ASSESSMENT_START_COUNTER',
  UNREAD_MESSAGES_THREADS_INITIATED_BY_COUNTER = 'UNREAD_MESSAGES_THREADS_INITIATED_BY_COUNTER',
  PENDING_EXPORT_REQUESTS_COUNTER = 'PENDING_EXPORT_REQUESTS_COUNTER'
};

export enum OrganisationUnitStatisticsEnum {
  INNOVATIONS_PER_UNIT = 'INNOVATIONS_PER_UNIT'
};
