const PROD_DOMAIN = 'https://innovation.nhs.uk';

export const URLS = {
  ABOUT_NICE: 'https://www.nice.org.uk/about',
  ABOUT_THE_SERVICE: `${PROD_DOMAIN}/about-the-service`,
  ACCESSIBILITY_STATEMENT: `${PROD_DOMAIN}/accessibility-statement`,
  ADVANCED_INNOVATION_GUIDE: `${PROD_DOMAIN}/innovation-guides/advanced-innovation-guide`,
  AHSN_NETWORK: 'https://www.ahsnnetwork.com/',
  COMISSIONING_AND_ADOPTION: `${PROD_DOMAIN}/innovation-guides/commissioning-and-adoption`,
  CONTACT_US: `${PROD_DOMAIN}/contact-us`,
  CORE20PLUS5: 'https://www.england.nhs.uk/about/equality/equality-hub/national-healthcare-inequalities-improvement-programme/core20plus5',
  DELIVERING_A_NET_ZERO_NHS: 'https://www.england.nhs.uk/greenernhs/wp-content/uploads/sites/51/2022/07/B1728-delivering-a-net-zero-nhs-july-2022.pdf',
  ENABLE_JAVASCRIPT_SUPPORT: 'https://support.microsoft.com/en-us/office/enable-javascript-7bb9ee74-6a9e-4dd1-babf-b0a1bb136361',
  HEALTH_TECHNOLOGY: 'https://www.healthtechnology.wales/',
  HOTJAR_SURVEY: 'https://surveys.hotjar.com/8e2b12c2-150d-4704-9b09-4df3a791e51b',
  INNOVATION_GUIDES: `${PROD_DOMAIN}/innovation-guides`,
  INTELLECTUAL_PROPERTY: `${PROD_DOMAIN}/innovation-guides/creation/intellectual-property`,
  LIFE_SCIENCES_ORGANISATION: 'https://www.gov.uk/government/organisations/life-sciences-organisation',
  LSHUBWALES: 'https://lshubwales.com/',
  MEDICAL_DEVICES_INTENDED_PURPOSE_STATEMENT: 'https://www.digitalregulations.innovation.nhs.uk/developers-guidance/all-developers-guidance/medical-devices-intended-purpose-statement',
  MY_RESEARCH_PROJECT: 'https://www.myresearchproject.org.uk',
  NHS_DIGITAL_TECHNOLOGY_ASSESSMENT_CRITERIA: 'https://www.digitalregulations.innovation.nhs.uk/developers-guidance/all-developers-guidance/nhs-digital-technology-assessment-criteria-dtac/?triage_system=Medical%20device',
  NHSRHO: 'https://www.nhsrho.org',
  NIHR: 'https://www.nihr.ac.uk/',
  ORGANISATIONS_BEHIND_THE_SERVICE: `${PROD_DOMAIN}/about-the-service/who-we-are#The%20organisations%20behind%20the%20service`,
  PRIVACY_NOTICE: 'https://www.england.nhs.uk/contact-us/privacy-notice',
  PRIVACY_POLICY: `${PROD_DOMAIN}/privacy-policy`,
  REGULATION: `${PROD_DOMAIN}/innovation-guides/regulation`,
  SAFARI_SUPPORT: 'https://support.apple.com/en-gb/guide/safari/ibrw1074/14.0/mac/11.0',
  SHTG: 'https://shtg.scot/',
  STARTER_INNOVATION_GUIDE: `${PROD_DOMAIN}/innovation-guides/starter-innovation-guide`,
  SUPPLIERS: 'https://www.england.nhs.uk/greenernhs/get-involved/suppliers/',
  SUPPLY_CHAIN: 'https://www.supplychain.nhs.uk/',
  TOU: `${PROD_DOMAIN}/terms-of-use`,
  TOU_INNOVATOR: `${PROD_DOMAIN}/terms-of-use/innovator`,
  TOU_SUPPORT_ORGANISATION: `${PROD_DOMAIN}/terms-of-use/support-organisation`,
  UNDERSTANDING_CQC_REGULATIONS: 'https://www.digitalregulations.innovation.nhs.uk/developers-guidance/all-developers-guidance/understanding-cqc-regulations/?triage_system=Medical%20device',
  UNDERSTANDING_REGULATIONS_MEDICAL_DEVICES: 'https://www.digitalregulations.innovation.nhs.uk/developers-guidance/all-developers-guidance/uk-mdr-2002-understanding-regulations-medical-devices/?triage_system=Medical%20device',
  USER_RESEARCH_FORM: 'https://forms.office.com/Pages/ResponsePage.aspx?id=kp4VA8ZyI0umSq9Q55CtvztdgIut6i1ClsC8hAncvh9UN0E2UEVON09BNjNMS1daRjZVMFJHRkNaMCQlQCN0PWcu',
  WHO_WE_ARE: `${PROD_DOMAIN}/about-the-service/who-we-are`,
}
